blank_issues_enabled: true
contact_links:
  - name: 💬 Discussions
    url: https://github.com/shuldeshoff/doc-mlops-pipeline/discussions
    about: Задавайте вопросы и обсуждайте проект
  - name: 📚 Documentation
    url: https://github.com/shuldeshoff/doc-mlops-pipeline#readme
    about: Читайте документацию проекта
  - name: 📞 Telegram
    url: https://t.me/shuldeshoff
    about: Связаться с автором напрямую

